#!/usr/bin/env python3
"""Generate wholly invented Citi credit-card regression fixtures."""

from pathlib import Path

PAGE_W, PAGE_H = 612, 792
FONT_SIZE = 9
LINE_H = 13
OUT = Path(__file__).resolve().parent.parent / "fixtures" / "citi-costco-synthetic-sample.pdf"
ANNUAL_OUT = Path(__file__).resolve().parent.parent / "fixtures" / "citi-annual-synthetic-sample.pdf"


def escape(value: str) -> bytes:
    return value.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)").encode("latin-1")


def build_pdf(pages: list[list[str]]) -> bytes:
    out = bytearray(b"%PDF-1.4\n")
    offsets: dict[int, int] = {}

    def add(number: int, body: bytes):
        offsets[number] = len(out)
        out.extend(f"{number} 0 obj\n".encode())
        out.extend(body)
        out.extend(b"\nendobj\n")

    page_objects = [4 + 2 * index for index in range(len(pages))]
    add(1, b"<< /Type /Catalog /Pages 2 0 R >>")
    add(2, f"<< /Type /Pages /Kids [{' '.join(f'{n} 0 R' for n in page_objects)}] /Count {len(pages)} >>".encode())
    add(3, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    for index, lines in enumerate(pages):
        page_number = page_objects[index]
        content_number = page_number + 1
        add(page_number, (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W} {PAGE_H}] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {content_number} 0 R >>"
        ).encode())
        stream = bytearray()
        y = PAGE_H - 45
        for line in lines:
            stream.extend(f"BT /F1 {FONT_SIZE} Tf 1 0 0 1 40 {y} Tm (".encode())
            stream.extend(escape(line))
            stream.extend(b") Tj ET\n")
            y -= LINE_H
        add(content_number, f"<< /Length {len(stream)} >>\nstream\n".encode() + stream + b"endstream")

    xref = len(out)
    out.extend(f"xref\n0 {max(offsets) + 1}\n0000000000 65535 f \n".encode())
    for number in range(1, max(offsets) + 1):
        out.extend(f"{offsets[number]:010d} 00000 n \n".encode())
    out.extend(f"trailer\n<< /Size {max(offsets) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode())
    return bytes(out)


pages = [
    [
        "www.citicards.com Costco Anywhere Visa Card by Citi",
        "Account number ending in: 4455",
        "SEPTEMBER STATEMENT",
        "Billing Period: 08/15/26-09/14/26",
        "Account Summary",
        "Previous balance $300.00",
        "Payments -$300.00",
        "Credits -$25.00",
        "Purchases +$410.00",
        "Cash advances +$0.00",
        "Fees +$0.00",
        "Interest +$0.00",
        "New balance $385.00",
    ],
    [
        "Page 2 of 2",
        "www.citicards.com Costco Anywhere Visa Card by Citi",
        "Account number ending in: 4455",
        "ACCOUNT SUMMARY",
        "Sale Post",
        "Date Date Description Amount",
        "Payments, Credits and Adjustments",
        "09/10 AUTOPAY 260807000000000RAUTOPAY AUTO-PMT -$300.00",
        "09/11 09/11 COSTCO WHSE #0100 SAMPLE CITY CA -$25.00",
        "CARDHOLDER ONE",
        "Standard Purchases",
        "08/21 08/21 SAMPLE FERRY TERMINAL WA $45.00",
        "08/24 08/24 SAMPLE EV CHARGING CA $15.00",
        "08/30 08/30 WWW COSTCO COM WA $100.00",
        "09/04 09/04 COSTCO WHSE #0100 SAMPLE CITY CA $250.00",
        "Fees Charged",
        "TOTAL FEES FOR THIS PERIOD $0.00",
        "Interest Charged",
        "TOTAL INTEREST FOR THIS PERIOD $0.00",
        "Interest charge calculation",
    ],
]

OUT.write_bytes(build_pdf(pages))
print(OUT)

annual_pages = [
    [
        "This report was generated by Citi Card Benefits",
        "Annual account summary (2025)",
        "ALICE EXAMPLE | account ending 1111",
        "BOB EXAMPLE | account ending 2222",
        "Totals by Category                         Total by Month",
        "ALICE EXAMPLE",
        "Air Travel",
        "Date Description Amount Notes",
        "Feb 09, 2025 SAMPLE AIRLINE SEATTLE WA $100.00",
        "Feb 02, 2025 SAMPLE AIRLINE PORTLAND OR $50.00",
        "Subtotal $150.00",
        "Merchandise",
        "Date Description Amount Notes",
        "Dec 28, 2025 REDACTED MERCHANT WA xxxxxxx",
        "Dec 24, 2025 SAMPLE MARKET SAN JOSE CA $50.00",
        "Merchandise continues...",
        "If you earn rewards by category, your rewards may be higher or lower than you expect.",
        "Read more about this on your rewards website.",
    ],
    [
        "Annual account summary (2025)",
        "ALICE EXAMPLE | account ending 1111",
        "BOB EXAMPLE | account ending 2222",
        "Merchandise",
        "Date Description Amount Notes",
        "Nov 03, 2025 SAMPLE WEB STORE WA $25.00",
        "Subtotal xxxxxxx",
        "BOB EXAMPLE",
        "Merchandise",
        "Date Description Amount Notes",
        "Oct 17, 2025 SAMPLE WAREHOUSE CA $200.00",
        "Oct 16, 2025 SAMPLE WAREHOUSE RETURN CA -$20.00",
        "Subtotal $180.00",
        "Vehicle Services",
        "Date Description Amount Notes",
        "Sep 14, 2025 SAMPLE FUEL CA $40.00",
        "Subtotal $40.00",
        "If you earn rewards by category, your rewards may be higher or lower than you expect.",
        "Read more about this on your rewards website.",
    ],
]

ANNUAL_OUT.write_bytes(build_pdf(annual_pages))
print(ANNUAL_OUT)
